server:
  port: 8090
logging :
  level :
   com.spring.project : Debug
   root : Debug
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_vendor?useSSL=false
    username: root
    password: MySQL8@#

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER


 #JPA Settings
    jpa.hibernate.ddl_auto: create-update
